# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "i2c-dev"];
  boot.initrd.kernelModules = [ ]; # Doesnt work [ "coretemp" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/212b65fc-8a1d-4e45-b358-601d60d526e9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9D41-A7BD";
      fsType = "vfat";
    };

    swapDevices = [
      { label = "swap"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  nix.buildCores = 0; # Use all cores of your CPU
  # ^^^^^^^^^^ Some builds may become non-deterministic with this option
}
